name: tempcord
description: Profiled body temperature recorder for animals.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  fluent_ui: ^3.9.1
  fluentui_icons: ^1.0.0
  fluentui_system_icons: ^1.1.163
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.1.0
  sqflite: ^2.0.2
  sqlite3_flutter_libs: ^0.5.4
  sqflite_common_ffi: ^2.1.0+2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: a738913
  meta: ^1.7.0
  path: ^1.8.0
  path_provider: ^2.0.9
  google_fonts: ^2.3.1
  url_launcher: ^6.0.20
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  generate: true